server {
    listen 16017;

    # redirect old links
    port_in_redirect off;

    location /investing {
        return 301 "https://www.edinburghventurepoint.com/contact#scout-programme";
    }

    location /meet-the-team {
        return 301 "https://www.edinburghventurepoint.com/about#meet-the-team";
    }

    location /partners {
        return 301 "https://www.edinburghventurepoint.com/contact#network";
    }


    # main config
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /static/ {
        alias /var/www/django/static/; 
    }

    location /api/ {
        proxy_pass http://backend:17017;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://backend:17017;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}