services:
  frontend:
    ports:
      - "16016:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:17017
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    environment:
      - DEBUG=True