# Generated by Django 6.0.5 on 2026-07-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupentry',
            options={'ordering': ('-created_at',), 'verbose_name': 'Startup', 'verbose_name_plural': 'Startups'},
        ),
    ]
