# Generated by Django 6.0.5 on 2026-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('scout', 'Scout'), ('committee', 'Committee')], default='member', max_length=20),
        ),
    ]
