# Generated by Django 6.0.5 on 2026-07-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='code_hash',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='consumed_at',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='code',
            field=models.CharField(default='935544', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
    ]
