# Generated by Django 6.0.5 on 2026-09-04 15:46

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(default=apps.accounts.models.generate_hashed_otp_code, editable=False, max_length=64),
        ),
    ]
