# Generated by Django 6.0.5 on 2026-07-31 11:31

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_emailotp_code_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(default=apps.accounts.models.generate_otp_code, editable=False, max_length=6),
        ),
    ]
