# Generated by Django 6.0.5 on 2026-07-31 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailotp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
