# Generated by Django 6.0.5 on 2026-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailotp_expires_at_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_newsletter_emails',
            field=models.BooleanField(default=True, help_text='Unsubscribe from newsletter emails'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
